# Generated by Django 4.0.1 on 2022-01-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=200)),
                ('pub_date', models.DateField(verbose_name='Date Published')),
                ('num_words', models.IntegerField(verbose_name='Number of Characters')),
                ('blog_tags', models.TextField(verbose_name='Comma seperated tags')),
                ('text_body', models.TextField(verbose_name='Blog text body')),
            ],
        ),
    ]
