# Generated by Django 4.0.1 on 2022-02-03 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogosphere', '0002_blogentry_plain_text_alter_blogentry_num_words_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogentry',
            name='plain_text',
        ),
    ]
