# Generated by Django 4.0.1 on 2022-02-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogosphere', '0003_remove_blogentry_plain_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='docs_url',
            field=models.TextField(default='', verbose_name='Docs URL code'),
            preserve_default=False,
        ),
    ]
