# Generated by Django 4.0.1 on 2022-02-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogosphere', '0005_alter_blogentry_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='blog_tags',
            field=models.TextField(null=True, verbose_name='Comma seperated tags'),
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='docs_url',
            field=models.TextField(null=True, verbose_name='Docs URL code'),
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='num_words',
            field=models.IntegerField(null=True, verbose_name='Number of Words'),
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='text_body',
            field=models.TextField(null=True, verbose_name='Raw HTML'),
        ),
    ]
