# Generated by Django 4.0.1 on 2022-02-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogosphere', '0006_alter_blogentry_blog_tags_alter_blogentry_docs_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='raw_text',
            field=models.TextField(null=True, verbose_name='Plain document text'),
        ),
    ]
