# Generated by Django 4.0.1 on 2022-02-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogosphere', '0007_blogentry_raw_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='blog_tags',
            field=models.TextField(blank=True, null=True, verbose_name='Comma seperated tags'),
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='blog_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='num_words',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Words'),
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='pub_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='raw_text',
            field=models.TextField(blank=True, null=True, verbose_name='Plain document text'),
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='text_body',
            field=models.TextField(blank=True, null=True, verbose_name='Raw HTML'),
        ),
    ]
